[package]
name = "lxp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.37", features = ["derive"] }

[dependencies.lxp-daemon-connector]
path = "../daemon-connector"

[dependencies.lxp-common]
path = "../common"
