[package]
name = "lxp-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
colorize = "0.1.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
tabled = "0.18.0"
uuid = { version = "1.16.0", features = ["v4"] }